Master Notes for Data Analysis Class
========================================================
****
## Assignment due date: February 16 EST
****
#### Directories
```{r, echo=TRUE}
Data<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/WorkingData")
Description<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Description")
Explore<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Explore")
Graphs<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Graphs")
Munging<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Munging")
Notes<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Notes")
Reports<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Reports")
Tests<-("/Users/Teleak/Desktop/RCourse/DataAnalysis/AnalysisAssignment1/Rproject/Tests")
```
```{r, downloaded}
downloaded<-date() ###"Sun Feb  3 20:25:46 2013"
downloaded
```